### ISSUE TITLE
关于测试集和testcases的两个问题

### ISSUE THREAD

**Issue by Symbolk** [aixcoder-plugin/nl2code-dataset#7]
首先感谢公开本测试集！

其次，有两个问题没有在README中看到，烦请回答一下：

1. 测试集是否与AiXCoder模型的训练集隔离？
2. testcases是从原项目收集的吗？还是人工补充的呢？

**Comment by felixhao28** [comment]
> 1. 测试集是否与AiXCoder模型的训练集隔离？

测试集都是在抓取的数据集上手工修改而来的。从源头上，并没有和训练集产生交集。但我们也没有用最终获得的测试数据集对训练数据做专门的去重，因为编写这个数据集的时候，模型已经训练完了。

> 2. testcases是从原项目收集的吗？还是人工补充的呢？

全都是人工补充的。

**Comment by Symbolk** [comment]
嗯嗯，感谢回复！

我查看了一下，这个测试集是否只包含注释部分，仓库中的代码实现好像都是不同模型预测的结果而并未包含抓取数据集的原始实现？

**Comment by felixhao28** [comment]
> 嗯嗯，感谢回复！
> 
> 我查看了一下，这个测试集是否只包含注释部分，仓库中的代码实现好像都是不同模型预测的结果而并未包含抓取数据集的原始实现？

对，由于功能描述说明是人工写/改出来的，自然也不包含抓取的原始实现。

**Comment by Symbolk** [comment]
> > 嗯嗯，感谢回复！
> > 我查看了一下，这个测试集是否只包含注释部分，仓库中的代码实现好像都是不同模型预测的结果而并未包含抓取数据集的原始实现？
> 
> 对，由于功能描述说明是人工写/改出来的，自然也不包含抓取的原始实现。

谢谢！
